### ISSUE TITLE
Laravel 5.0 compatibility

### ISSUE THREAD

**Issue by foxted** [foxted/Permissions#5]
Make the package compatible with Laravel 5.0

**Comment by kodeine** [comment]
Any ideas when it will be compatible for l5?

**Comment by foxted** [comment]
I'll bump the version in the composer.json file this week. I'll update the codebase to leverage the contracts once L5 will be released ;)

**Comment by foxted** [comment]
Version 1.4.0 now support Laravel 5

**Comment by kodeine** [comment]
thanks.
